// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJWRWEYwDw1br-_ieaw3u2yScs6gWZdTM',
    appId: '1:734101647473:web:9c4ee3d73b9ff603c82bd0',
    messagingSenderId: '734101647473',
    projectId: 'flutterchatapp-22f9b',
    authDomain: 'flutterchatapp-22f9b.firebaseapp.com',
    storageBucket: 'flutterchatapp-22f9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtv35KFmO8TLjw43p-aDEf3E9MXd_u-cs',
    appId: '1:734101647473:android:be619510f247beafc82bd0',
    messagingSenderId: '734101647473',
    projectId: 'flutterchatapp-22f9b',
    storageBucket: 'flutterchatapp-22f9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbvQUMXy_YNGsiyfN25ozcCxzvZcnRr40',
    appId: '1:734101647473:ios:1e4b752085ecaafac82bd0',
    messagingSenderId: '734101647473',
    projectId: 'flutterchatapp-22f9b',
    storageBucket: 'flutterchatapp-22f9b.appspot.com',
    iosClientId: '734101647473-j237lp65qvgprfrn3i3tf7jouv5c7eca.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatProject',
  );
}
